Name:-Ritesh Rajendra Salunkhe

Subject:-Practical to data mining

Course:-Msc.Data Science and big data analytics

Student id:-4497945

In [ ]:
import pandas as pd

In [ ]:
#movies dataset
df1 = pd.read_csv('/content/Movies.csv', encoding='ISO-8859-1')

In [ ]:
df1.head()

,MovieID,Title,Category,Unnamed: 3,Unnamed: 4
0,1,Toy Story (1995),Animation|Children's|Comedy,NaN,NaN
1,2,Jumanji (1995),Adventure|Children's|Fantasy,NaN,NaN
2,3,Grumpier Old Men (1995),Comedy|Romance,NaN,NaN
3,4,Waiting to Exhale (1995),Comedy|Drama,NaN,NaN
4,5,Father of the Bride Part II (1995),Comedy,NaN,NaN

In [ ]:
df1.isnull().sum()

MovieID          0
Title            0
Category         0
Unnamed: 3    3719
Unnamed: 4    3882
dtype: int64

In [ ]:
df1.drop(columns=['Unnamed: 3', 'Unnamed: 4'], inplace=True)

In [ ]:
new_df1 = pd.DataFrame(df1)
new_df1['ReleaseYear'] = new_df1['Title'].str.extract(r'\((\d{4})\)', expand=False)
new_df1['ReleaseYear'] = pd.to_numeric(new_df1['ReleaseYear'], errors='coerce').fillna(0).astype(int)
new_df1['Category'] = new_df1['Category'].str.split('|')

In [ ]:
new_df1.head()

,MovieID,Title,Category,ReleaseYear
0,1,Toy Story (1995),"[Animation, Children's, Comedy]",1995
1,2,Jumanji (1995),"[Adventure, Children's, Fantasy]",1995
2,3,Grumpier Old Men (1995),"[Comedy, Romance]",1995
3,4,Waiting to Exhale (1995),"[Comedy, Drama]",1995
4,5,Father of the Bride Part II (1995),[Comedy],1995

In [ ]:
#rating dataset
df2 =pd.read_csv('/content/Ratings.csv')

In [ ]:
new_df2 = pd.DataFrame(df2)

In [ ]:
new_df2

         UserID  MovieID  Rating
0             1     1193       5
1             1      661       3
2             1      914       3
3             1     3408       4
4             1     2355       5
...         ...      ...     ...
1000204    6040     1091       1
1000205    6040     1094       5
1000206    6040      562       5
1000207    6040     1096       4
1000208    6040     1097       4

[1000209 rows x 3 columns]

In [ ]:
new_df2.isnull().sum()

UserID     0
MovieID    0
Rating     0
dtype: int64

In [ ]:
#user dataset
df3 = pd.read_csv('/content/Users.csv')

In [ ]:
new_df3 = pd.DataFrame(df3)

In [ ]:
new_df3

      UserID Gender  Age  Occupation
0          1      F    1          10
1          2      M   56          16
2          3      M   25          15
3          4      M   45           7
4          5      M   25          20
...      ...    ...  ...         ...
6035    6036      F   25          15
6036    6037      F   45           1
6037    6038      F   56           1
6038    6039      F   45           0
6039    6040      M   25           6

[6040 rows x 4 columns]

In [ ]:
new_df3.isnull().sum()

UserID        0
Gender        0
Age           0
Occupation    0
dtype: int64

***Question 1***

In [ ]:
# 1) Total number of movies released in each year

movies_peryear = new_df1.groupby('ReleaseYear').size().reset_index(name='Count')
print(movies_peryear)

    ReleaseYear  Count
0             0    164
1          1919      2
2          1920      2
3          1921      1
4          1922      2
..          ...    ...
77         1996    327
78         1997    300
79         1998    323
80         1999    273
81         2000    150

[82 rows x 2 columns]

In [ ]:
movies_peryear = new_df1['ReleaseYear'].value_counts().reset_index()
movies_peryear.columns = ['ReleaseYear', 'Count']
print("1) Total number of movies released in each year:")
print(movies_peryear)

1) Total number of movies released in each year:
    ReleaseYear  Count
0          1995    335
1          1996    327
2          1998    323
3          1997    300
4          1999    273
..          ...    ...
77         1923      3
78         1922      2
79         1919      2
80         1920      2
81         1921      1

[82 rows x 2 columns]

***Question 2***

In [ ]:
# 2) Find the movie category having highest ratings in each year. The output should comprise of YearofRelease, Category, CountOfMovies having highest rating.

merged_df = new_df2.merge(new_df1, on='MovieID')
merged_df['Category'] = merged_df['Category'].apply(lambda x: ','.join(x))
# Finding highest rating categories per year
category_ratings_per_year = merged_df.groupby(['ReleaseYear', 'Category'])['Rating'].mean().reset_index()
highest_rated_category_per_year = category_ratings_per_year.loc[category_ratings_per_year.groupby('ReleaseYear')['Rating'].idxmax()]
print(highest_rated_category_per_year)

      ReleaseYear                                           Category    Rating
54              0   How I Learned to Stop Worrying and Love the B...  4.449890
162          1919                                             Comedy  3.631579
163          1920                                             Comedy  3.666667
164          1921                                             Action  3.790323
165          1922                                             Horror  3.991597
...           ...                                                ...       ...
1360         1996                               Crime,Drama,Thriller  4.254676
1442         1997                   Crime,Film-Noir,Mystery,Thriller  4.219406
1485         1998                                   Action,Drama,War  4.119213
1561         1999                        Animation,Children's,Comedy  4.218927
1602         2000                                       Action,Drama  4.106029

[82 rows x 3 columns]

***Questions 3***

In [ ]:
# 3) Find and display movie category and age group wise likings. This may be based on the highest number of users from each age group rated for that movie category.

complete_df = merged_df.merge(df3, on='UserID')

# Aggregating by Category and Age Group
age_group_category_likes = complete_df.groupby(['Age', 'Category']).size().reset_index(name='Count')
most_liked_categories_per_age_group = age_group_category_likes.loc[age_group_category_likes.groupby('Age')['Count'].idxmax()]
print("\n3) Movie category and age group wise likings:")
print(most_liked_categories_per_age_group)

3) Movie category and age group wise likings:
      Age Category  Count
296     1   Comedy   3454
736    18   Comedy  22556
1184   25   Comedy  45605
1694   35    Drama  22368
2131   45    Drama  10408
2568   50    Drama   9686
2968   56    Drama   6078

***Questions 4***

In [ ]:
# 4) Use Cluster models to segregate movie category and age group wise likings.

from sklearn.cluster import KMeans

# Preparing data for clustering
clustered_data = complete_df[['Age', 'Category']].copy()
clustered_data['Category'] = clustered_data['Category'].astype('category').cat.codes  # Encoding categories

# Running K-means clustering
kmeans = KMeans(n_clusters=2, random_state=0).fit(clustered_data)
clustered_data['Cluster'] = kmeans.labels_

print(clustered_data.groupby(['Cluster', 'Category']).size().reset_index(name='Count'))

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

     Cluster  Category  Count
0          0         0    199
1          0         1    416
2          0         2      8
3          0         3    110
4          0         4    114
..       ...       ...    ...
450        1       449   4702
451        1       450    280
452        1       451  17791
453        1       452    991
454        1       453   5689

[455 rows x 3 columns]

***Question 5***

In [ ]:
# 5) Display year wise count of movies released

print(movies_peryear)

    ReleaseYear  Count
0          1995    335
1          1996    327
2          1998    323
3          1997    300
4          1999    273
..          ...    ...
77         1923      3
78         1922      2
79         1919      2
80         1920      2
81         1921      1

[82 rows x 2 columns]

***Question 6***

In [ ]:
# 6) Display year wise, category wise count of movies released.

merged_df['Category'] = merged_df['Category'].apply(lambda x: ','.join(x))
movies_per_year_category = new_df1.groupby(['ReleaseYear', new_df1['Category'].str[0]]).size().reset_index(name='Count')
print(movies_per_year_category)

     ReleaseYear                          Category  Count
0              0                         3D (1982)      1
1              0         A Cinderella Story (1998)      1
2              0        A Journal of Murder (1995)      1
3              0   A Mediaeval Odyssey, The (1988)      1
4              0            A New Beginning (1985)      1
..           ...                               ...    ...
778         2000                             Drama     36
779         2000                            Horror      3
780         2000                           Romance      1
781         2000                            Sci-Fi      2
782         2000                          Thriller      6

[783 rows x 3 columns]

***Question 7***

In [ ]:
# 7) Use Clustering methods to segregate movie category and occupation of users. Display details. With the data, train the model and predict that when an occupation is entered, the model can predict the movie likings to that category of occupation.

# Preparing data for clustering
clustered_data = complete_df[['Occupation', 'Category']].copy()
clustered_data['Category'] = clustered_data['Category'].astype('category').cat.codes  # Encoding categories

# Running K-means clustering
kmeans = KMeans(n_clusters=3, random_state=0).fit(clustered_data)
clustered_data['Cluster'] = kmeans.labels_

# Displaying clustered data
clustered_details = clustered_data.groupby(['Cluster', 'Occupation', 'Category']).size().reset_index(name='Count')
print(clustered_details)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

      Cluster  Occupation  Category  Count
0           0           0       262     56
1           0           0       263    265
2           0           0       264    123
3           0           0       265    184
4           0           0       266     12
...       ...         ...       ...    ...
8586        2          20       449    288
8587        2          20       450     18
8588        2          20       451   1023
8589        2          20       452     67
8590        2          20       453    340

[8591 rows x 4 columns]

In [ ]:
# Predicting Movie Likings Based on Occupation

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Preparing the dataset
x = clustered_data[['Occupation']]
y = clustered_data['Category']

# Splitting the dataset
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

# Training the model
model = RandomForestClassifier(random_state=42)
model.fit(xtrain, ytrain)

# Converting the 'Category' column to categorical data type
complete_df['Category'] = complete_df['Category'].astype('category')

# Predicting for a new occupation
new_occupation = [[10]]  # Example occupation
predicted_category_code = model.predict(new_occupation)
predicted_category = complete_df['Category'].cat.categories[predicted_category_code[0]]
print(f"Predicted movie category for occupation {new_occupation[0][0]}: {predicted_category}")

Predicted movie category for occupation 10: Comedy

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

***Question 8***

In [ ]:
# 8) the age group to the above model in addition to occupation of users to refine the predictive model.


# Check if 'Age' column exists in complete_df
if 'Age' in complete_df.columns:
    # Add 'Age' column to cluster_data
    clustered_data['Age'] = complete_df['Age']
else:
    raise ValueError("Column 'Age' not found in complete_df")

# Continue with the code as before

# Preparing the dataset
x = clustered_data[['Occupation', 'Category']]
y = clustered_data['Age']

# Splitting the dataset
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

# Training the model
model = RandomForestClassifier(random_state=42)
model.fit(xtrain, ytrain)

# Predicting for a new occupation and age group
new_data = [[10, 25]]  # Example occupation and age group
predicted_category_code = model.predict(new_data)
predicted_category = complete_df['Category'].cat.categories[predicted_category_code[0]]
print(f"Predicted movie category for occupation {new_data[0][0]} and age {new_data[0][1]}: {predicted_category}")

Predicted movie category for occupation 10 and age 25:  A Cinderella Story (1998)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

***Questions 9***

In [ ]:
# 9) Develop another model, where the search key should be category of movie, the answer should be the most likely age group of users and type of occupations associated. This model should be trained based on category of movies with age group and occupation who likes the most.

# Preparing the dataset
x = clustered_data[['Category']]
y = clustered_data[['Age', 'Occupation']]

# Splitting the dataset
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

# Training the model
model = RandomForestClassifier(random_state=42)
model.fit(xtrain, ytrain)

# Predicting for a new movie category
new_category_code = [[complete_df['Category'].cat.codes[0]]]  # Example category code
predicted_values = model.predict(new_category_code)
predicted_age, predicted_occupation = predicted_values[0]
print(f"Predicted age group and occupation for movie category {new_category_code[0][0]}: Age {predicted_age}, Occupation {predicted_occupation}")

Predicted age group and occupation for movie category 395: Age 25, Occupation 0

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [31]:
# Simple User Interface for querying and displaying results

def main():
    print("\n***** Movie Recommendation System *****")
    while True:
        print("\nSelect an option:")
        print("1. Display year-wise count of movies released")
        print("2. Find highest rated category per year")
        print("3. Find most liked category by age group")
        print("4. Cluster category likes by age group")
        print("5. Display year wise count of movies released.")
        print("6. Display year wise, category wise count of movies released.")
        print("7. Clustering methods to segregate movie category and occupation of users")
        print("8. Predicting Movie Likings Based on Occupation")
        print("9. Cluster category likes by occupation and age group")
        print("10. Predict age group and occupation based on movie category")
        print("0. Exit")


        choice = input("Enter your choice (1-10): ")

        if choice == '1':
          print(movies_peryear)
        elif choice == '2':
          print(highest_rated_category_per_year)
        elif choice == '3':
          print(most_liked_categories_per_age_group)
        elif choice == '4':
          print(clustered_data)
        elif choice == '5':
          print(movies_peryear)
        elif choice == '6':
          print(movies_per_year_category)
        elif choice =='7':
          print(clustered_details)
        elif choice == '8':
          occupation = input("Enter Occupation: ")
          predicted_category = complete_df['Category'].cat.categories[predicted_category_code[0]]
          print(f"Predicted movie category for occupation {new_occupation[0][0]}: {predicted_category}")
        elif choice == '9':
          occupation = input("Enter Occupation: ")
          age_group = input("Enter Age Group: ")
          predicted_category = complete_df['Category'].cat.categories[predicted_category_code[0]]
          print(f"Predicted movie category for occupation {new_data[0][0]} and age {new_data[0][1]}: {predicted_category}")
        elif choice == '10':
          movie_category = input("Enter Movie Category: ")
          predicted_age, predicted_occupation = predicted_values[0]
          print(f"Predicted age group and occupation for movie category {new_category_code[0][0]}: Age {predicted_age}, Occupation {predicted_occupation}")
          print(f"\nFor movie category '{movie_category}':")
          print(f"Predicted Age Group: {predicted_age}")
          print(f"Predicted Occupation: {predicted_occupation}")
        elif choice == '0':
          print("Exiting the program. Goodbye!")
          break
        else:
          print("Invalid choice. Please enter a number from 0 to 10.")

if __name__ == "__main__":
    main()

***** Movie Recommendation System *****

Select an option:
1. Display year-wise count of movies released
2. Find highest rated category per year
3. Find most liked category by age group
4. Cluster category likes by age group
5. Display year wise count of movies released.
6. Display year wise, category wise count of movies released.
7. Clustering methods to segregate movie category and occupation of users
8. Predicting Movie Likings Based on Occupation
9. Cluster category likes by occupation and age group
10. Predict age group and occupation based on movie category
0. Exit
Enter your choice (1-10): 1
    ReleaseYear  Count
0          1995    335
1          1996    327
2          1998    323
3          1997    300
4          1999    273
..          ...    ...
77         1923      3
78         1922      2
79         1919      2
80         1920      2
81         1921      1

[82 rows x 2 columns]

Select an option:
1. Display year-wise count of movies released
2. Find highest rated category per year
3. Find most liked category by age group
4. Cluster category likes by age group
5. Display year wise count of movies released.
6. Display year wise, category wise count of movies released.
7. Clustering methods to segregate movie category and occupation of users
8. Predicting Movie Likings Based on Occupation
9. Cluster category likes by occupation and age group
10. Predict age group and occupation based on movie category
0. Exit
Enter your choice (1-10): 2
      ReleaseYear                                           Category    Rating
54              0   How I Learned to Stop Worrying and Love the B...  4.449890
162          1919                                             Comedy  3.631579
163          1920                                             Comedy  3.666667
164          1921                                             Action  3.790323
165          1922                                             Horror  3.991597
...           ...                                                ...       ...
1360         1996                               Crime,Drama,Thriller  4.254676
1442         1997                   Crime,Film-Noir,Mystery,Thriller  4.219406
1485         1998                                   Action,Drama,War  4.119213
1561         1999                        Animation,Children's,Comedy  4.218927
1602         2000                                       Action,Drama  4.106029

[82 rows x 3 columns]

Select an option:
1. Display year-wise count of movies released
2. Find highest rated category per year
3. Find most liked category by age group
4. Cluster category likes by age group
5. Display year wise count of movies released.
6. Display year wise, category wise count of movies released.
7. Clustering methods to segregate movie category and occupation of users
8. Predicting Movie Likings Based on Occupation
9. Cluster category likes by occupation and age group
10. Predict age group and occupation based on movie category
0. Exit
Enter your choice (1-10): 3
      Age Category  Count
296     1   Comedy   3454
736    18   Comedy  22556
1184   25   Comedy  45605
1694   35    Drama  22368
2131   45    Drama  10408
2568   50    Drama   9686
2968   56    Drama   6078

Select an option:
1. Display year-wise count of movies released
2. Find highest rated category per year
3. Find most liked category by age group
4. Cluster category likes by age group
5. Display year wise count of movies released.
6. Display year wise, category wise count of movies released.
7. Clustering methods to segregate movie category and occupation of users
8. Predicting Movie Likings Based on Occupation
9. Cluster category likes by occupation and age group
10. Predict age group and occupation based on movie category
0. Exit
Enter your choice (1-10): 4
         Occupation  Category  Cluster  Age
0                10       395        2    1
1                10       309        0    1
2                10       437        2    1
3                10       395        2    1
4                10       302        0    1
...             ...       ...      ...  ...
1000204           5       395        2   45
1000205           5       453        2   45
1000206           5       429        2   45
1000207           5       251        1   45
1000208           5       284        0   45

[1000209 rows x 4 columns]

Select an option:
1. Display year-wise count of movies released
2. Find highest rated category per year
3. Find most liked category by age group
4. Cluster category likes by age group
5. Display year wise count of movies released.
6. Display year wise, category wise count of movies released.
7. Clustering methods to segregate movie category and occupation of users
8. Predicting Movie Likings Based on Occupation
9. Cluster category likes by occupation and age group
10. Predict age group and occupation based on movie category
0. Exit
Enter your choice (1-10): 5
    ReleaseYear  Count
0          1995    335
1          1996    327
2          1998    323
3          1997    300
4          1999    273
..          ...    ...
77         1923      3
78         1922      2
79         1919      2
80         1920      2
81         1921      1

[82 rows x 2 columns]

Select an option:
1. Display year-wise count of movies released
2. Find highest rated category per year
3. Find most liked category by age group
4. Cluster category likes by age group
5. Display year wise count of movies released.
6. Display year wise, category wise count of movies released.
7. Clustering methods to segregate movie category and occupation of users
8. Predicting Movie Likings Based on Occupation
9. Cluster category likes by occupation and age group
10. Predict age group and occupation based on movie category
0. Exit
Enter your choice (1-10): 6
     ReleaseYear                          Category  Count
0              0                         3D (1982)      1
1              0         A Cinderella Story (1998)      1
2              0        A Journal of Murder (1995)      1
3              0   A Mediaeval Odyssey, The (1988)      1
4              0            A New Beginning (1985)      1
..           ...                               ...    ...
778         2000                             Drama     36
779         2000                            Horror      3
780         2000                           Romance      1
781         2000                            Sci-Fi      2
782         2000                          Thriller      6

[783 rows x 3 columns]

Select an option:
1. Display year-wise count of movies released
2. Find highest rated category per year
3. Find most liked category by age group
4. Cluster category likes by age group
5. Display year wise count of movies released.
6. Display year wise, category wise count of movies released.
7. Clustering methods to segregate movie category and occupation of users
8. Predicting Movie Likings Based on Occupation
9. Cluster category likes by occupation and age group
10. Predict age group and occupation based on movie category
0. Exit
Enter your choice (1-10): 8
Enter Occupation: 0
Predicted movie category for occupation 10:  A Cinderella Story (1998)

Select an option:
1. Display year-wise count of movies released
2. Find highest rated category per year
3. Find most liked category by age group
4. Cluster category likes by age group
5. Display year wise count of movies released.
6. Display year wise, category wise count of movies released.
7. Clustering methods to segregate movie category and occupation of users
8. Predicting Movie Likings Based on Occupation
9. Cluster category likes by occupation and age group
10. Predict age group and occupation based on movie category
0. Exit
Enter your choice (1-10): 0
Exiting the program. Goodbye!